=== sujinee0010/Library-program/booklist.dtd
<!ELEMENT booklist (book+)>
<!ELEMENT book (title, author, publisher, price, ISBN)>
<!ATTLIST book
          kind CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>

=== sujinee0010/Library-program/booklist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">
<booklist>
	<book kind="컴퓨터">
		<title>XML 웹 서비스</title>
		<author>옹길동</author>
		<publisher>옹출판사</publisher>
		<price>20000</price>
		<ISBN>110-21-961065-0-7</ISBN>
	</book>
	<book kind="소설">
		<title>금붕어메세지</title>
		<author>이능문</author>
		<publisher>생각과기억</publisher>
		<price>9000</price>
		<ISBN>110-21-961065-0-8</ISBN>
	</book>
	<book kind="컴퓨터">
		<title>Java And XML</title>
		<author>홍길동</author>
		<publisher>영진 출판사</publisher>
		<price>25000</price>
		<ISBN>110-21-961065-0-9</ISBN>
	</book>
</booklist>
